name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  url_launcher: ^6.0.9
  http: ^0.13.3 
  webview_flutter: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

assets:
  - assets/1.jpg

flutter:
  uses-material-design: true